// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GoodsExchange.data.Models;

public partial class Comment
{
    public int CommentId { get; set; }

    public DateTime DateTime { get; set; }

    public int PostId { get; set; }

    public int CustomerId { get; set; }

    public string Content { get; set; }

    public string Title { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual Post Post { get; set; }
}