// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GoodsExchange.data.Models;

public partial class Post
{
    public int PostId { get; set; }

    public string Address { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public DateTime CreateDate { get; set; }

    public int PostOwnerId { get; set; }

    public DateTime? ExchangeDate { get; set; }

    public int CategoryId { get; set; }

    public virtual Category Category { get; set; }

    public virtual ICollection<Comment> Comments { get; set; } = new List<Comment>();

    public virtual ICollection<OfferDetail> OfferDetails { get; set; } = new List<OfferDetail>();

    public virtual Customer PostOwner { get; set; }
}